version: '3'
services:
  nginx:
    image: nginx:1.21.5-alpine
    ports:
      - "8090:80"
    volumes:
      - ./.nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/usr/share/nginx/html/website
