name: Surge PR Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  preview:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # allow surge-preview to create/update PR comments
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: afc163/surge-preview@v1
        env:
          MY_SITE_BASE: /
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          failOnError: true
          build: |
            pnpm i
            pnpm run build
          dist: dist

      - name: Get the preview_url
        run: echo "url => ${{ steps.preview_step.outputs.preview_url }}"
